# Generated by Django 2.2.2 on 2019-09-25 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Reservation',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='ReservationInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtime', models.CharField(choices=[('10:00-17:00', '10:00-17:00'), ('9:00-13:00', '9:00-13:00'), ('13:00-17:00', '13:00-17:00'), ('17:00-21:00', '17:00-21:00')], max_length=20)),
                ('your_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('reservation_date', models.DateField()),
                ('age_ofthechild', models.CharField(max_length=200)),
                ('allergies', models.TextField(blank=True, max_length=2000, null=True)),
                ('vaccinations', models.CharField(blank=True, max_length=1000, null=True)),
                ('illness', models.CharField(blank=True, max_length=1000, null=True)),
                ('travel_insurance', models.CharField(blank=True, max_length=1000, null=True)),
                ('wifi', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Nursery')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Reservation')),
            ],
            options={
                'db_table': 'ReservationItem',
            },
        ),
    ]
