# Generated by Django 2.2.2 on 2019-10-24 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_nursery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('child_age', models.CharField(max_length=200)),
                ('allergy', models.TextField(blank=True, max_length=2000, null=True)),
                ('vaccination', models.CharField(blank=True, max_length=1000, null=True)),
                ('illness', models.CharField(blank=True, max_length=1000, null=True)),
                ('travel_insurance', models.CharField(blank=True, max_length=1000, null=True)),
                ('wifi', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Nursery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reservation',
                'ordering': ['date_created'],
            },
        ),
    ]
