# Generated by Django 2.2.2 on 2019-10-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
