# Generated by Django 2.2.2 on 2019-10-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20191024_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='allergy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='child_age',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='travel_insurance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vaccination',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='wifi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
