# Generated by Django 2.2.2 on 2019-10-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191024_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
