# Generated by Django 2.2.2 on 2019-10-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20191024_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_period',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_price',
            new_name='price',
        ),
    ]
