# Generated by Django 2.2.2 on 2019-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20191024_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='child_age',
            field=models.IntegerField(),
        ),
    ]
