# Generated by Django 2.2.2 on 2019-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20191025_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentStatus',
            field=models.CharField(default='NotPayed', max_length=50),
        ),
    ]
