# Generated by Django 2.2.2 on 2019-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_payment_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymentStatus',
        ),
        migrations.AddField(
            model_name='reservation',
            name='paymentStatus',
            field=models.CharField(default='NotPayed', max_length=50),
        ),
    ]
