# Generated by Django 2.2.2 on 2019-11-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20191029_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='child_age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
