# Generated by Django 2.2.2 on 2019-11-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20191101_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['created_at']},
        ),
    ]
